### ISSUE TITLE
Different line colors for threshold 

### ISSUE THREAD

**Issue by bernatfortet** [hshoff/vx#245]
I'm trying to create a chart where the line has a different color if it's above or below given a data point.

What approach would you recommend?
Is the idea to create multiple different line charts for each section of color?

Here's an example:
![image](https://user-images.githubusercontent.com/390010/36438904-1ddcd0b0-1620-11e8-990f-a2656ba7d004.png)

Thanks in advance!

**Comment by williaster** [comment]
Great question @bernatfortet! We were just discussing adding a "divided line" component to `@vx/shape` to enable doing this. Do you have a requirement to use areas or would lines suffice for you? (it'd be nice to have both ...)

If you're interested in helping add this component we would totally welcome a PR! Otherwise we'll try to get to it soon. If you want a quick solution for a divided line, check out this [vx code snippet](https://codesandbox.io/s/v36nj074o7) (screenshot below) that uses a linear gradient to define multiple colors (based on [this d3 block](https://bl.ocks.org/mbostock/3970883)). I think for the actual component implementation we would likely choose to have multiple `<path />`s in order to support the area use case. 

![image](https://user-images.githubusercontent.com/4496521/36442153-a6847fb8-1629-11e8-82e2-04d19c6f1ae8.png)

**Comment by jfilipe** [comment]
I was able to use the SVG `clipPath` property to accomplish that. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath

![image](https://user-images.githubusercontent.com/185875/36449546-12339760-1659-11e8-8a51-4454da9cc6a5.png)

Basically, I'm rendering the line twice in both colours, and then create 2 `clipPath`s to hide the line where it shouldn't be shown.

**Comment by bernatfortet** [comment]
Thanks @williaster!
I can give it a try within the next couple of weeks.

I updated the code example to mimic what I wanted. Indeed there's some piece of code to make it work with multiple areas. Right now the area start from the base.
![image](https://user-images.githubusercontent.com/390010/36451115-cca5887a-1644-11e8-95f8-292103455961.png)

https://codesandbox.io/s/qlw0x164j6

**Comment by bernatfortet** [comment]
![image](https://user-images.githubusercontent.com/390010/36940430-8489bb86-1ef7-11e8-9bed-dda22d35fd05.png)
I've updated to the code sandbox to reflect @jfilipe's idea of using clip paths.

@williaster, would you want me to create a component from this code sandbox?

**Comment by williaster** [comment]
thanks @bernatfortet! that looks great! 🎉 when I click the sandbox link above tho I still see the first version (where red starts at 0). any chance it has a different url?

either way, yeah if you're down to post a PR to move that to a component in `@vx/shape` that'd be 🙌I bet many people would use this.

**Comment by bernatfortet** [comment]
Oh, sorry: here's the new link link: https://codesandbox.io/s/8yxp82r3qj

I'll try to post a PR.
